### ISSUE TITLE
Feature: Allow every cms user to edit their password

### ISSUE THREAD

**Issue by daniel-de-wit** [czim/laravel-cms-core#3]

**Comment by czim** [comment]
I think it would be best if this were a separate module. Just make a simple module that adds this functionality and allow users to either make it part of the menu, or to somehow make it part of the top toolbar, f.i.

Correct me if you disagree, but I don't think this makes sense as a hard-coded part of the core.

**Comment by daniel-de-wit** [comment]
I'm confused as to where to put these general ideas for the CMS as a whole

**Comment by czim** [comment]
I guess you're right! This is probably the best repository for them. I will tag these as such to avoid further confusion.
