### ISSUE TITLE
Feature: Invite new CMS user

### ISSUE THREAD

**Issue by daniel-de-wit** [czim/laravel-cms-core#4]
Add option to invite a new CMS user via email. After loggin in with their temporary link / password, they should be forced to enter a new password.

**Comment by czim** [comment]
Sounds good. I'm tentatively wondering whether this might make sense as a (configurable) part of the ACL module. I also think the actual mailing should hook into a(n overridable) Laravel mailing strategy somehow.

**Comment by czim** [comment]
I'm closing this issue due to lack of interest
